### ISSUE TITLE
Ability to preview linked pages

### ISSUE THREAD

**Issue by Gaelan** [huggle/huggle#9]
Let's say someone who did not know much about US culture was reviewing an edit that added [[John Lennon]] to the list of members of a sports team. This person would likely either assume the edit was correct, or have to look up John Lennon separately to check. Showing summaries of articles on hover (similar to Hovercards) would solve this. How hard would this be?

**Comment by benapetr** [comment]
Probably easy, but keep in mind that huggle is feature frozen, you probably want to upgrade to huggle 3.

This repository is for huggle (0 - 2)

**Comment by Gaelan** [comment]
Ahh, I am using Huggle 3. Oops!
